---
apiVersion: v1
kind: Namespace
metadata:
  name: simple
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: simpleapiconfig
  namespace: simple
data:
  APPLICATIONINSIGHTS_CONNECTION_STRING: {{ print .Values.ai.connection_string | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api
  namespace: simple
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: simple-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: simple-api
        image: {{ print .Values.image.repository "/simple-api:" .Values.image.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 5501
        resources:
          limits:
            memory: "512Mi"
            cpu: "2"
          requests:
            memory: "64Mi"
            cpu: "0.25"
        envFrom:
        - configMapRef:
            name: simpleapiconfig
---
apiVersion: v1
kind: Service
metadata:
  name: simple-api-svc
  namespace: simple
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: simple-api
  ports:
  - port: 80
    targetPort: 5501
  type: LoadBalancer
