name: Trigger an ACR build (Self-Hosted)

on:
    workflow_dispatch: {}

env:
    AZURE_CONTAINER_REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
    CONTAINER_NAME: simple-api

jobs:
    buildImage:
        permissions:
            contents: read
            id-token: write
        runs-on: arc-runner-set
        steps:
            - uses: actions/checkout@v3
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.SIMPLE_REGISTRY_USERNAME }}
                password: ${{ secrets.SIMPLE_REGISTRY_PASSWORD }}
            
            - name: 'Build and push image'
              uses: azure/docker-login@v1
              with:
                login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
                username: ${{ secrets.SIMPLE_REGISTRY_USERNAME }}
                password: ${{ secrets.SIMPLE_REGISTRY_PASSWORD }}
            - run: |
                docker build . -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}/${{ env.CONTAINER_NAME }}:${{ github.sha }} -f ./src/dockerfile ./src
                docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}