name: Trigger the Creation of an Azure Container Apps Environment 

on:
  workflow_dispatch:      

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 

      - name: Create Azure Containerapp Environment
        uses: azure/CLI@v1
        with:
          inlineScript: |
            cd infrastructure
            az group create -n ${{ secrets.CONTAINER_APP_RG }} -l eastus2
            az deployment group create -n ${{ secrets.CONTAINER_APP_NAME }} -g ${{ secrets.CONTAINER_APP_RG }} -f ./main.bicep