name: Trigger auto deployment for simple

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - 'src/dockerfile/**'
    - '.github/workflows/simple-AutoDeployTrigger-5111a3fd-79df-40a2-a061-9c667e7eb510.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.SIMPLE_REGISTRY_USERNAME }}
          password: ${{ secrets.SIMPLE_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: bjd145/simple:${{ github.sha }}
          file: src/dockerfile
          context: src


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SIMPLE_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n simple -g ContainerApp_RG --server https://index.docker.io/ --username  ${{ secrets.SIMPLE_REGISTRY_USERNAME }} --password ${{ secrets.SIMPLE_REGISTRY_PASSWORD }}
            az containerapp update -n simple -g ContainerApp_RG --image docker.io/bjd145/simple:${{ github.sha }}
